### ISSUE TITLE
Interface with external visualizer

### ISSUE THREAD

**Issue by diegoferigo** [ami-iit/jaxsim#11]
JAXsim for the time being does not include any GUI nor visualizer to show the simulated models. While prototyping, I used [`gazebosim/gz-gui`](https://github.com/gazebosim/gz-gui) part of Gazebo Sim, but I think it's a dependency too large that would make deployment quite challenging.

It would be quite interesting using `gazebosim/gz-gui` as standalone visualizer, but I never saw anything based on it. 

Alternatively, [`rdeits/meshcat-python`](https://github.com/rdeits/meshcat-python) could be a valid and slim alternative, but in the past I couldn't manage to obtain acceptable performance in real-time usage. The problem is that all nodes (link poses) had to be refreshed individually. However, few months ago, https://github.com/duburcqa/jiminy/pull/543 implemented a method to update all nodes together, and it's worth a try.

**Comment by diegoferigo** [comment]
I created [`ami-iit/meshcat-viz-python`](https://github.com/ami-iit/meshcat-viz-python) to play with MeshCat, hoping to achieve better real-time performance by optimizing the client/server protocol that streams link transforms.

It would be also useful (but with much lower priority) being able to tweak the control menu of the web interface. I opened https://github.com/rdeits/meshcat-python/issues/128 for asking implementation details.

**Comment by fl-ferr** [comment]
As discussed F2F, the code relative to the visualization loop that allows to visualize the contact forces using [`meshcat-viz`](https://github.com/ami-iit/meshcat-viz-python) can be found in [ami-iit/element_rl-for-codesign/.../hopper.py](https://github.com/ami-iit/element_rl-for-codesign/blob/bdd54da5fd63c8b6262bb24e9b0ad9d41e136b4c/src/JAXsim/hopper.py#LL257C1-L282C1):

<details>
<summary>Visualization Loop</summary>

```python
for t in range(len(x_t.base_position[0]))[::downsampling]:
    for env_id in range(len(model_names)):
        world.update_model(
            model_name=model_names[env_id],
            joint_names=model.joint_names(),
            joint_positions=x_t.joint_positions[env_id][t],
            base_position=x_t.base_position[env_id][t],
            base_quaternion=x_t.base_quaternion[env_id][t],
        )

        # Compute the forces expressed in the right frame for visualization
        CL_fc_ext = world_to_viz_contact_forces(
            model,
            x_t.base_position[env_id][t],
            x_t.base_quaternion[env_id][t],
            x_t.joint_positions[env_id][t],
            time_history[model.name()].aux["t0"]["contact_forces_points"][env_id][t],
        )[:, 0:3]

        # Update the visualized contact forces
        for idx, (CL_fc, name) in enumerate(zip(CL_fc_ext, parent_link_name)):
            contacts[env_id][f"{name}_{idx}"].force.set(force=np.array(CL_fc))

        rate.sleep()
```
</details>

**Comment by diegoferigo** [comment]
I guess that we eventually converged towards the usage of the passive Mujoco viewer in #83. Closing.
