### ISSUE TITLE
Cannot run example notebooks with pixi on Ubuntu 22.04

### ISSUE THREAD

**Issue by xela-95** [ami-iit/jaxsim#140]
When I try to run the notebooks in the [examples](https://github.com/ami-iit/jaxsim/tree/main/examples) folder using pixi (as one of the methods suggested in the documentation) I get the following error:

```console
  × failed to parse project manifest
    ╭─[pixi.toml:11:1]
 10 │ cuda = "12"
 11 │ unix = true
    · ──┬─
    ·   ╰── unknown field `unix`, expected one of `macos`, `linux`, `cuda`, `libc`, `archspec`
 12 │ 
    ╰────
```

My system is Ubuntu 22.04 and I'm using the main commit a6544fb9c1663caea2b73daebd0faa379080cf79

**Comment by traversaro** [comment]
I think this was a change in pixi. The `unix` system-requirement was removed in https://github.com/prefix-dev/pixi/pull/632 (pixi 0.12.0). I think we can directly remove it, as anyhow there are no non-unix platforms listed in https://github.com/ami-iit/jaxsim/blob/a6544fb9c1663caea2b73daebd0faa379080cf79/examples/pixi.toml#L6, so I do not see the point of having `unix` there (full disclosure: I am probably the one that put it there in the first place in https://github.com/traversaro/mujoco-mjx-pixi-example .
