### ISSUE TITLE
Add more advanced example notebooks

### ISSUE THREAD

**Issue by flferretti** [ami-iit/jaxsim#194]
As the library starts to have more users, the need for a more complete documentation and examples naturally emerges, as seen in #175 and #187. For this reason, this issue aims at showing more than the basics JaxSim features already presented in the [existing notebooks](https://github.com/amii-iit/jaxsim/blob/main/examples). 

The idea is both to improve the existing examples by simplifying the visualisation logic when using headless rendering and to add one or more notebooks with more advanced use-cases using e.g. reinforcement learning or model-based control architectures.

**Comment by diegoferigo** [comment]
Having more examples that are automatically tested in CI would be great (and in our case, after #187, readthedocs would fail to render if a notebook is not running). I have some very old examples from late 2021 that were quite nice. Nothing fancy, just simple simulations, but there were a nice showcase of the simulation potential. Now that we can render them in our documentation, it's probably worth bringing them back. We can talk about this f2f.
