### ISSUE TITLE
Add a scheduled workflow to automatically update the `pixi.lock` file

### ISSUE THREAD

**Issue by diegoferigo** [ami-iit/jaxsim#199]
It would be nice to have a scheduled workflow (let's say, once per month) that re-creates from scratch a new `pixi.lock` file and run the tests on the new dependencies. If successful, a new PR can be automatically opened so that the new file can be pushed to LFS.

This would allow to maintain a rolling-release set of working dependencies attached to the git repository.

Related to #189.

**Comment by flferretti** [comment]
A possible idea could be to modify https://pixi.sh/dev/advanced/updates_github_actions/#how-to-use integrating LFS and logging some diff in the PR description.

**Comment by diegoferigo** [comment]
Yep, we already discussed this in https://github.com/ami-iit/jaxsim/pull/189#issuecomment-2194525004.
