### ISSUE TITLE
Port on notebooks the existing GPU simulations of model 

### ISSUE THREAD

**Issue by traversaro** [ami-iit/jaxsim#60]
First step (cartpole):
* Show simulation
* Show how we can use "complex functions" such as gravity compensation by changing the controller to use of PD+gravity compensation

Second step (ergocub):
* Show simulation

I would keep the two in two different notebooks as the second one requires a separate dependency.

**Comment by flferretti** [comment]
Check out the `Development` section for the related working branch

**Comment by traversaro** [comment]
I tried to add a visualization based on iDynTree, but I forgot that in iDynTree on PyPI I disabled the irrlicht deps in https://github.com/robotology/idyntree/pull/1068, so I get as error:
~~~
[ERROR] ModelLoader :: loadModelFromFile : Error in parsing model from URDF.
[ERROR] Visualizer :: init : Impossible to use iDynTree::Visualizer, as iDynTree has been compiled without Irrlicht.
[ERROR] Visualizer :: addModel : Impossible to use iDynTree::Visualizer, as iDynTree has been compiled without Irrlicht.
[ERROR] Visualizer :: drawToFile : Impossible to call drawToFile in a not initialized visualizer
~~~

**Comment by flferretti** [comment]
We could try to use the conda version of IDynTree using [`condacolab`](https://github.com/conda-incubator/condacolab). Otherwise, tomorrow I will work on the use of `pixi` to make the example easier to use

**Comment by flferretti** [comment]
In https://github.com/ami-iit/jaxsim/commit/856d06e4a6a58e6e08fdf12d7fde83c50b804485 I added `pixi` support for `linux-64` and `osx-64`, where the latter uses [JAX Metal](https://developer.apple.com/metal/jax/) for GPU support on Apple Silicon. As it is still in experimental phase, we can think of dropping support for the examples on OSX, for the time being

**Comment by flferretti** [comment]
Notebook added in #63. Closing
