### ISSUE TITLE
Package project in conda-forge

### ISSUE THREAD

**Issue by diegoferigo** [ami-iit/jaxsim#7]
This is a long-sighted issue, and it aims to collect the information to enable the installation of jaxsim with the following single command:

```
mamba install -c conda-forge jaxsim
```

---

Missing dependencies in conda-forge:

- https://github.com/brentyi/jax_dataclasses
- https://github.com/FirefoxMetzger/scikit-bot

The first one should be rather easy to package in conda-forge, the second a bit less. Before moving forward, I'd like to check if we can replace it with [FirefoxMetzger/python-sdformat/](https://github.com/FirefoxMetzger/python-sdformat/) since we only need it to parse SDF files.

I also have an experimental visualizer based on ScenarIO (https://github.com/conda-forge/staged-recipes/pull/16582), but it does not work properly with the last versions of Gazebo Sim and we should find a fix.

**Comment by fl-ferr** [comment]
With https://github.com/conda-forge/staged-recipes/pull/23968, JAXsim will only need a tagged released to be published in `conda-forge` :tada:

**Comment by flferretti** [comment]
PR for `rod` and `distrax` merged (https://github.com/conda-forge/staged-recipes/pull/23968 and https://github.com/conda-forge/staged-recipes/pull/23973). 
An additional PR on `tensorflow-probability` (https://github.com/conda-forge/tensorflow-probability-feedstock/pull/50) that required a major change in the installation mode has been also merged to make `distrax` work. 
No other dependencies on conda-forge needed

**Comment by flferretti** [comment]
Please check out: https://github.com/conda-forge/staged-recipes/pull/24630

**Comment by flferretti** [comment]
The package is now available in [conda-forge](https://github.com/conda-forge/jaxsim-feedstock). Closing
